//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeChallan()
        {
            this.StudentChallans = new HashSet<StudentChallan>();
        }
    
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentChallan> StudentChallans { get; set; }
    }
}
