//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitHomework
    {
        public int Id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> HomeworkID { get; set; }
        public string HomeworkContent { get; set; }
    
        public virtual ClassHomework ClassHomework { get; set; }
        public virtual Student Student { get; set; }
    }
}
