//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public string Lec1 { get; set; }
        public string Lec2 { get; set; }
        public string Lec3 { get; set; }
        public string Lec4 { get; set; }
        public string Lec5 { get; set; }
        public string Lec6 { get; set; }
        public string Lec7 { get; set; }
        public string Lec8 { get; set; }
        public string Day { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
    }
}
