//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int Id { get; set; }
        public int TeacherID { get; set; }
        public Nullable<int> Pay { get; set; }
        public string Designation { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
